# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

# TODO - Review the workflow. Make it leaner.
#         Should have less steps;
#         Should have steps with clearer name;

# Workflow name
name: E2E Workflow

on:
  schedule:
    - cron: '0 12 * * *'
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  # ESLint check
  eslint:
    name: ESLint verification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: ESLint check
        run: |
          npm ci
          npm run eslint

  # Cy run with repport - v2
  cypress-run:
    name: Test execution
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.17.0-chrome91-ff89
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install project
        run: |
          npm ci
          $(npm bin)/cypress cache path
          $(npm bin)/cypress cache list
          $(npm bin)/cypress verify

      - name: Run E2E tests
        run: |
          npm run test:chrome
          mkdir public
          cp -r cypress/videos public/videos
          npm run report:merge
          npm run report:generate
        continue-on-error: false

      - name: Save report
        uses: actions/upload-artifact@v4
        with:
          path: public/videos/

      # - name: Save report data
      #   run: |
      #     mkdir public
      #     cp -r cypress/videos public/videos
      #     npm run report:merge
      #     npm run report:generate

  report-deploy:
    name: Report deploy
    runs-on: ubuntu-latest
    needs: cypress-run
    steps:
      - name: Download report
        uses: actions/download-artifact@v4

      - name: Deploy report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'

      # - name: Prepare report

      #   # 1st - Copy test execution videos
      #   # 2nd - Merge test results into one
      #   # 3rd - Generate HTML report
      #   run: |
      #     mkdir public
      #     cp -r cypress/videos public/videos
      #     npm run report:merge
      #     npm run report:generate

      # # Deploy report
      # - name: Deploy report
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./public
      #     user_name: 'github-actions[bot]'
      #     user_email: 'github-actions[bot]@users.noreply.github.com'
